### PR TITLE
Added functionality to turn all duplicates into gems

### PR DESCRIPTION
**Pull request by slimDebug**
I just wanted to turn all my duplicate items into gems. To be fair this is the first time for me doing stuff in JS, but `sellAllDuplicateItems()` was already providing a mechanism to filter out all duplicate items. So this part wasn't this hard. I tried to follow the general code style as well.
Preview of the new button:
image

Feel free to give me any input. Like I said JS is kinda new for me.

This relates to #170.

### CODE REVIEW

**Comment by Nuklon** [comment]
Can you undo the whitespace changes? The rest seems OK.

**Comment by slimDebug** [comment]
Done 👍

**Comment by slimDebug** [comment]
If you mean mean the tabs I introduced (instead of spaces), I just removed them. I also removed some additional tabs that I found while I was doing it.

**Comment by Revadike** [comment]
thief!

**Pull request merged**
